services:

  backend:
    image: arcar13/frenchcab-backend:latest
    ports:
      - "127.0.0.1:3001:3001"

    environment:
      - DB_RELATIONNELLE=/data/frenchcab_relationnelle.db
      - MODEL_PATH=/app/ML/modele_temps_trajet.pkl

    volumes :
      - /opt/frenchcab/data/raw_data:/raw_data
      - /opt/frenchcab/data/db:/data

  gateway:
    image: arcar13/frenchcab-gateway:latest
    environment:
      - BACKEND_URL=http://backend:3001

    ports:
      - "3000:3000"

  frontend:
    image: arcar13/frenchcab-frontend:latest

    # Port du front sur l'hôte (FRONT_PORT dans .env, 4200 par défaut)
    ports:
      - "${FRONT_PORT:-4200}:80"

    depends_on:
      - gateway
