services:

  backend:
    image: arcar13/yellowcab:frenchcab-backend

    ports:
      - "127.0.0.1:3001:3001"

  gateway:
    image: arcar13/frenchcab-gateway:latest
    environment:
      - BACKEND_URL=http://backend:3001

    ports:
      - "3000:3000"

  frontend:
    image: arcar13/yellowcab:frenchcab-frontend

    ports:
      - "127.0.0.1:4200:4200"

    # volumes:
    #   - /app/node_modules

    command: npm start -- --host 0.0.0.0 --port 4200
